server:
  port: 8080

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/"
      path-mapping:
        health: "health"
        info: "info"

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/compose-postgres
    username: compose-postgres
    password: compose-postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5