server:
  port: 8080

management:
  server:
    port: 9001
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/"
      path-mapping:
        health: "health"
        info: "info"